---
abstract: 'Create calendars with reserved slots'
author:
  - 'Rodrigo de Oliveira <rodrigolive@gmail.com>'
generated_by: 'Dist::Zilla::Plugin::MetaYAML version 1.092450'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Calendar-Slots
requires:
  Carp: 0
  DateTime::Format::Strptime: 0
  Moose: 0
  MooseX::AttributeHelpers: 0
  Test::More: 0.9
version: 0.03
