---
abstract: 'Create calendars with reserved slots'
author:
  - 'Rodrigo de Oliveira <rodrigolive@gmail.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300021, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Calendar-Slots
requires:
  Carp: 0
  DateTime::Format::Strptime: 0
  Moose: 0
  Moose::Util::TypeConstraints: 0
  MooseX::AttributeHelpers: 0
  Test::More: 0.9
  namespace::autoclean: 0
version: 0.12
